title: CSS Reference ( 中文 )
subtitle: "視覺化 CSS 手冊"
description: "CSS Reference 整理最常使用到的 CSS 屬性，以動畫方式展示屬性效果"
share: "CSS Reference：整理最常使用到的 CSS 屬性，以動畫方式展示屬性效果"
url: http://localhost:4000
markdown: kramdown
permalink: pretty
exclude: ['node_modules']
